src/app/layout.tsx

nav is created

---

src/app/page.tsx

Shahriar created a branch to share his idea

create a new branch and change a code for testing purpose

---

src/app/page.tsx

new list added tow

---

src/app/about/page.tsx

added about route

---

next.config.ts
src/app/layout.tsx
src/app/page.tsx
src/components/homeComponents/TopRestaurant.tsx

Shahriar added some sections and fixed image errors

Shahriar added some sections and fixed image errors

---

package-lock.json
package.json
src/app/aboutUs/page.tsx
src/components/shared/Navbar.tsx
src/components/ui/dropdown-menu.tsx

I added dropdown menu for responsive on mobile, tablet and another device

navbar responsive is done

---

src/app/aboutUs/page.tsx

some update in about page

---

src/app/page.tsx
src/components/homeComponents/FeaturedFood.tsx
src/components/shared/SectionHeading.tsx

fix some errors in featured section

fix error 

---

src/app/aboutUs/page.tsx

some update in heading of about page

heading update in about page

---

src/app/page.tsx
src/components/homeComponents/banner.tsx
src/components/shared/button/ButtonComponent.tsx

change some tiny changes

---

package-lock.json
src/declarations.d.ts

changes declarations.d.ts file

[MODIFIED]: changes declarations.d.ts file

---

package-lock.json
src/components/shared/Navbar.tsx
src/lib/dbConnect.tsx

[ADDED]: added route in navbar

---

src/components/shared/Navbar.tsx

added signIn and signup in navbar

[ADDED]:signup and signIn added

---

src/components/shared/Navbar.tsx

[MODIFIED]:solve conflict

---

package-lock.json
package.json
src/app/action/auth/allApi.ts

[MODIFIED]: solve some conflict

---

package-lock.json
package.json
src/app/action/auth/allApi.ts

[MODIFY]: conflict solve

---

package.json
src/app/(dashboardLayout)/dashboard/resturantOwner/allFoodItem/page.tsx

[MODIFY]: modify all food route

[MODIFY]: modify all food route

---

package.json
src/app/(dashboardLayout)/dashboard/loading.tsx
src/app/(homeLayout)/loading.tsx
src/app/action/auth/allApi.ts

[ADDED]: added default loading for all route

[ADDED]: added default loading for all route

---

src/app/(dashboardLayout)/dashboard/page.tsx
src/middleware.ts

added role base show the dashboard route

[]: added role base show the dashboard route

---

src/app/(dashboardLayout)/dashboard/page.tsx
src/app/(dashboardLayout)/dashboard/resturantOwner/updateResturant/page.tsx
src/app/(dashboardLayout)/layout.tsx
src/app/(homeLayout)/allFood/page.tsx
src/app/(homeLayout)/beRider/page.tsx
src/app/action/auth/allApi.ts
src/components/shared/Navbar.tsx

[ADDED]: added update resturant route

[ADDED]: added update resturant route

---

.gitignore
src/app/(dashboardLayout)/dashboard/admin/allResturant/page.tsx
src/app/(dashboardLayout)/dashboard/admin/allRiders/page.tsx
src/app/(homeLayout)/beRider/page.tsx
src/app/action/auth/allApi.ts

All restaurant pages and all rider pages are done.

[DONE]: All restaurant page and all rider page done.

---

src/app/(dashboardLayout)/dashboard/admin/allResturant/page.tsx
src/app/(dashboardLayout)/dashboard/admin/allRiders/page.tsx

[UPDATED]: modify 2 pages

---

src/app/(dashboardLayout)/dashboard/admin/allResturant/page.tsx
src/app/(dashboardLayout)/dashboard/admin/allRiders/page.tsx
src/app/(dashboardLayout)/dashboard/admin/applications/page.tsx
src/app/(homeLayout)/beOwner/page.tsx
src/app/(homeLayout)/beRider/page.tsx
src/app/action/auth/allApi.ts
src/components/authentications/RegisterForm.tsx
src/middleware.ts

[Done]: Delete rider and restaurant

---

src/app/(dashboardLayout)/dashboard/resturantOwner/orderHistory/components/OrderHistoryTable.tsx
src/app/action/auth/allApi.ts

[ADDED]: restaurant order history button funbctionality

[ADDED]: restaurant order history button funbctionality
